# Makefile for ModularInverses_451

FLAGS = -std=c++20
FLAGS += -O2

bsoln : bsoln.cxx
	clear
	g++ bsoln.cxx toolbox.cxx $(FLAGS) -o ./bsoln
	
asoln : asoln.cxx
	clear
	g++ asoln.cxx toolbox.cxx $(FLAGS) -o ./asoln

query : queries.cxx
	g++ queries.cxx $(FLAGS) -o ./query
	
sqrs : squares.cxx
	g++ squares.cxx $(FLAGS) -o ./sqrs
	
