# Makefile for ModularInverses_451

FLAGS = -std=c++20

asoln : asoln.cxx
	g++ asoln.cxx toolbox.cxx $(FLAGS) -o ./asoln

query : queries.cxx
	g++ queries.cxx $(FLAGS) -o ./query
	
sqrs : squares.cxx
	g++ squares.cxx $(FLAGS) -o ./sqrs
	
